spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: 'false'
    suffix: .html
    check-template-location: 'true'
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

---
server:
  port: '8080'

management:
  server:
    port: '8081'

---
jwt:
  header: Authorization
  secret: aJKPulCiGigeJgI62waXkdr8aO1bydliU4La7Q
  securePath: /test/api

cipher:
  aesKey: +zZdkIvLB+U6hgUNNInTAaknQ6NRMKnm

---
tistory:
  apis:
    authorize:
      uri: 'https://www.tistory.com/oauth/authorize'
      state: 'tapsv1'
    accessToken:
      uri: 'https://www.tistory.com/oauth/access_token'

taps:
  aggregator-api:
    uri: http://localhost:8080
    authorize: /authorize/token