web:
  location:
    logout: ${WEB_LOCATION_SIGNIN}/logout
    signup: ${WEB_LOCATION_SIGNUP}
    index: ${WEB_LOCATION_INDEX}
    signin: ${WEB_LOCATION_SIGNIN}
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: 'false'
    suffix: .html
    check-template-location: 'true'
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    connect-timeout: 1000000

feign:
  client:
    config:
      default:
        logger-level: FULL
        read-timeout: '10000'
        connect-timeout: '5000'

auth:
  server:
    be:
      unionapi:
        base: ${AUTH_SERVER_BE_UNIONAPI}
        signup: /api/v1/auth/signup/newuser
        check:
          duplicate:
            email: /api/v1/check/duplicate/email
            nickname: /api/v1/check/duplicate/nickname

smtp:
  mail:
    server:
      base: ${SMTP_SERVER_BASE}
      send:
        signupAuthMail:
          url: /api/v1/mail/send/signupForAuth
      verify:
        signupAuthMail:
          url: /api/v1/mail/verify/signupForAuth

server:
  port: '8080'

logging:
  level:
    io:
      github:
        rojae:
          authsignupweb: debug

management:
  endpoints:
    web:
      exposure:
        include: prometheus