spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: 'false'
    suffix: .html
    check-template-location: 'true'

---
server:
  port: '8080'

---
tistory:
  apis:
    authorize:
      uri: 'https://www.tistory.com/oauth/authorize'
      state: 'tapsv1'
    accessToken:
      uri: 'https://www.tistory.com/oauth/access_token'